// <auto-generated />
using System;
using InForm.Server.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InForm.Server.Migrations
{
    [DbContext(typeof(InFormDbContext))]
    [Migration("20240209162227_StringForms")]
    partial class StringForms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("InForm")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InForm.Features.Forms.Db.Form", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Subtitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Forms", "InForm");
                });

            modelBuilder.Entity("InForm.Features.Forms.Db.FormElementBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<long?>("ParentFormId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ParentFormId");

                    b.ToTable("FormElementBases", "InForm");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FormElementBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InForm.Features.Forms.Db.StringFormElement", b =>
                {
                    b.HasBaseType("InForm.Features.Forms.Db.FormElementBase");

                    b.Property<long?>("MaxLength")
                        .HasColumnType("bigint");

                    b.Property<bool>("RenderAsTextArea")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("StringFormElement");
                });

            modelBuilder.Entity("InForm.Features.Forms.Db.FormElementBase", b =>
                {
                    b.HasOne("InForm.Features.Forms.Db.Form", "ParentForm")
                        .WithMany("FormElementBases")
                        .HasForeignKey("ParentFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentForm");
                });

            modelBuilder.Entity("InForm.Features.Forms.Db.Form", b =>
                {
                    b.Navigation("FormElementBases");
                });
#pragma warning restore 612, 618
        }
    }
}
